### ISSUE TITLE
bilibili-helper 访问 secureweb24.net 的功能是？

### ISSUE THREAD

**Issue by enerai** [zacyu/bilibili-helper#35]
新版的 bilibili-helper 在启用之后会发送信息到 secureweb24.net 这个域名，即便没有访问 bilibili 主页，也会有如下的请求发送（通过 ublock origin 查看可得）

00:11:04				xhr	https://s1712.secureweb24.net/service2
00:11:04				xhr	https://s712.secureweb24.net/related
00:11:04				xhr	https://s1712.secureweb24.net/service2
00:11:00				xhr	https://s1712.secureweb24.net/service2
00:11:00				xhr	https://s712.secureweb24.net/related
00:10:46				xhr	https://s1712.secureweb24.net/service2
00:10:46				xhr	https://s712.secureweb24.net/related

想问一下作者访问这个域名是为了实现什么功能呢？

内容更新：
刚刚看到这个“本扩展加入了 SimilarWeb 提供的统计代码，用于统计用户匿名的使用数据 (包括 http 和 https 域)”，
不过根据观察，插件统计的是其他页面（非 bilibili.com，比如 weibo.com，youku.com）的数据，这也。。。有点奇怪吧。。。

而且 http 和 https 都有统计，这个实在是不让人放心。毕竟 SimilarWeb 这个网站自己也是要盈利的。不知道能不能加一个开关，让用户自己选择是否提交数据给 SimilarWeb？

**Comment by jabbany** [comment]
#33 流量追踪代码。用于统计使用者所有的互联网行为。目前来说是feature非bug。

**Comment by jabbany** [comment]
如果不想要追踪代码，可以考虑用这个https://github.com/jabbany/bilibili-helper-safe， 我打算在近期打包投webstore。开源软件好处就是不爽可以fork嘛 :)

**Comment by enerai** [comment]
我不明白这个 feature 的意义对作者或者对这个扩展的意义是什么。不过话说回来，作者的扩展做的还是不错的，我目前暂时屏蔽掉了往 SimilarWeb 服务器的后台上传请求。还没有想到其他的好办法。

**Comment by Zhuogu** [comment]
根据目前达成的协议, SimilarWeb 在给我提供用户使用情况的同时会将收集的非个人的统计数据用作商业用途 (如提供互联网趋势的商业分析), 但是所有的行为都会在相关[服务条款和隐私策略](http://addons-privacy.com/)的保护下.
使用了类似统计代码的 Chrome 扩展/应用 包括:
[crxMouse Chrome Gestures](https://chrome.google.com/webstore/detail/crxmouse-chrome-gestures/jlgkpaicikihijadgifklkbpdajbkhjo), [Facebook Notifications](https://chrome.google.com/webstore/detail/facebook-notifications/ainkhhbgcdbenmmbaoacambbhjfgnmmm), [Power Zoom](https://chrome.google.com/webstore/detail/power-zoom-zoom-images-wi/jlioidldolgbmanndggdnldambdlglgj)
不过鉴于你的顾虑, 我会在下一个版本中加入允许用户 opt-out 的选项.

**Comment by jabbany** [comment]
SimilarWeb的隐私条款其实还是有很多点非常堪忧的：
Our addon may use third-party advertising companies in order to serve advertisements. Such parties may use cookies placed on your computer in order to a adjust the advertisements presented on Our addon. （我们的代码可以允许第三方广告公司在你的计算机上放置追踪cookie。我们的代码有权向你推送广告。）

还有，加上tracking代码后插件应该加注儿童主意的标签：We do not offer our products or services for use by children. If you are under 18, you may not use the Extension or our Products without involvement of a parent or a guardian.

有关信息收集的部分也有各种堪忧的条款：
整个Browsing History章节有关IP地址收集的部分：Our addon may collect IP addresses之后的话都是在解释为何你不必担心收集IP地址，却并不作任何限制SimilarWeb出售地址和与地址相关的浏览信息到第三方的声明。同时根据这个章节，SimilarWeb不认为IP地址和浏览历史属于PII（可识个人信息），所以后面章节关于保护个人可识别信息的规定则不适用于这两者。

个人建议如果真的希望加analytics的话，Google Analytics专门有针对chrome扩展设计的，隐私条款要靠谱很多，而且据说提供信息也很全面。

希望作者重新考虑使用的追踪代码运营商，同时可能的情况下希望在下版内不要让插件默认请求所有站点所有信息的权限，而是把它挪到optional permissions区域。仅仅添加“opt out选项”却依然在主程序内请求高权限的话可信度还是值得商榷。

**Comment by Zhuogu** [comment]
@jabbany 隐私协议中关于 Third Party Advertisements 的部分我有和他们确定过, 只是因为他们提供了一个通用的隐私策略适用于所有的扩展, 所以加入了这一段, 而他们本身并不会防止用于推送广告的追踪 cookie. 没有使用 Google Analytics, 很重要的一个原因是因为 Bilibili Helper 的大多数用户都处在中国大陆地区, 而因为一些非 GA 产品本身的原因, 这部分用户通常都无法被统计到. 如果把更高的权限移到 optional_permissions 的问题是用户统计相当于就变成了 opt-in 从而失去了其本身的意义.
如果你认为 opt-out 不能提供有效保证的话, 我可以在你的 "bilibili-helper-safe" 版本上架 Chrome Webstore 后在我这边提供一个你的扩展地址链接, 引导和你有类似顾虑的用户安装你的降权后版本.

**Comment by jabbany** [comment]
也可以。

**Comment by enerai** [comment]
@jabbany 那个helper-safe访问显示404=_=

**Comment by Zhuogu** [comment]
@enerai 因为带了一个全角逗号, 我已经帮助修改了

**Comment by enerai** [comment]
@Zhuogu 囧，iPad上面默认不显示链接，没想到是这种原因。。
